### ISSUE TITLE
Overlapping level-ups freezing Runelite

### ISSUE THREAD

**Issue by GoldenBeanos** [m0bilebtw/c-engineer-completed#23] opened 2023-11-20 14:59 UTC
Getting several level-ups back to back due to leagues causes Runelite to freeze until the previous sound snippet has ended. Causing severe noticeable lag spikes cutting into gameplay.

**Comment by m0bilebtw** [comment] 2023-11-20 15:07
When did you last restart runelite? I've released an update that should've fixed this already

**Comment by GoldenBeanos** [comment] 2023-11-20 15:09
Ah, I haven't restarted for a few hours I'll do that! Thank you very much!

**Comment by m0bilebtw** [comment] 2023-11-20 15:15
Please let me know if it still happens after the restart

**Comment by pwatts6060** [comment] 2023-11-22 21:22
On the Tedious Collection Log fork there is considerable lag when the plugin announces the collection log. Best way to test this is buying and selling items at castle wars for collection log items. You'll notice the lag when you try sell the piece you just bought/buy the next piece after the collection log announcement. @evaan 
The issue isn't present in the C Engineer: Completed plugin however.

**Comment by m0bilebtw** [comment] 2023-11-22 21:25
It makes sense this issue is still present in the tedious plugin as they forked off of this plugin a long time ago but I only fixed the issue a couple of days ago. I'm not the maintainer of the tedious plugin but they're welcome to reference the change I made here recently to resolve the issue there too.

Thanks for additional confirmation that the fix is indeed working, closing this issue

**Closed by m0bilebtw** 2023-11-22 21:25 UTC
